### ISSUE TITLE
Add numpydoc-validation to pre-commit checks

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/topofileformats#39]
We use docstrings in this package and to be consistent and align with linting of TopoStats we should add [`numpydoc-validation`](https://github.com/numpy/numpydoc) to the suite of [pre-commit](https://pre-commit.com) hooks we have in place.

The following will add this.

```yaml
  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0
    hooks:
      - id: numpydoc-validation
```
